version: '3'

services:
  riderize-postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=riderize-ride
  riderize-redis-cache:
    image: redis:latest
    ports:
      - 6379:6379
