name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ee15adfc-b8e1-4ddc-9de1-01fb108cf002
          heroku_app_name: "riderize-ride-deploy" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"